### ISSUE TITLE
Projenin Özelliklerini Yaz

### ISSUE THREAD

**Issue by merbussa** [haticegunes/Document-Tracking-System#2]
<ul>
<li>PDF formatında doküman eklenecek.</li>
<li>Admin tarafından belirlenen kullanıcı girişi.</li>
<li>Admin gerekli dersleri ve kullanıcıları(öğretmen) ekleyecek.</li>
<li>Kullanıcılar sadece admin tarafından oluşturulacak.</li>
<li>Dokümanları sadece kullanıcılar girecek, düzenleyecek ve silecek.</li>
<li>Dokümanları herkes görebilecek.</li>
</ul>

**Comment by bibuggy** [comment]
Bu iş kaydında sadece sitede olması düşünülen özellikler veya davranışlar yazılır. Bu iş kaydı için konuşacak olursak, **reademe** kısmı gibi oluşturulmuş, bu kısım **readme** kısmında kullanılabilir. Aslında yazılış şöyle olmalıydı:

> - PDF formatında dokuman eklenecek.
> - Admin tarafından belirlenen kullanıcı girişi. 
> - Admin gerekli dersleri ve kullanıcıları(öğretmen) ekleyecek. (kullanıcılar sadece admin tarafından oluşturulacak)
> - Dokümanları sadece kullanıcılar girecek, düzenleyecek ve silecek.
> - Dokümanları herkes görebilecek.

**Comment by bibuggy** [comment]
Checklist şeklinde yazılan (Ruby on Rails projesi oluşturulacak) ayrı bir iş kaydı şeklinde oluşturulmalı.

**Comment by bibuggy** [comment]
## Bu iş kaydını anlatıldığı şekilde düzenle.

**Comment by mrym-bsr** [comment]
# İş kaydı istenilen şekilde düzelendi.
