### ISSUE TITLE
Modelleri Oluştur

### ISSUE THREAD

**Issue by merbussa** [haticegunes/Document-Tracking-System#3]
- [x] Model oluşturmayı öğren.
- [x] Model oluştur.
### Gerekli Modeller;

<ul>
<li>Lesson</li>
<li>Document</li>
</ul>

**Comment by bibuggy** [comment]
## Örnek davranış #4 numaralı iş kaydında anlatılmıştır. Diğer iş kayıtlarını da bu formatta yapın.

**Comment by merbussa** [comment]
Active Record; projemizde kullanılan modellerin aralarında ki ilişkisel (bir'e birlik bir'e çokluk) durumun haritalandırılmış halidir.

**Comment by merbussa** [comment]
Model çizimi oluşturuldu. 

![Alt text](http://yuml.me/28133aee)

**Comment by mrym-bsr** [comment]
# İş kaydı istenilen şekilde düzelendi.
