### ISSUE TITLE
Mock-Up Oluştur

### ISSUE THREAD

**Issue by merbussa** [haticegunes/Document-Tracking-System#4]
- [x] Mock-Up oluşturmayı öğren.
- [x] Mock-Up oluştur.

**Comment by bibuggy** [comment]
İş kaydının ilk comment'i içindekiler kısmı gibi olmalıdır. Yapılan iş ile ilgili açıklamalar sonraki comment'lerde anlatılır. Örneğin bu iş kaydın için konuşacak olursak aslında beklenen hareket şöyle olmalı:

> - [ ] Mock-Up oluşturmayı öğren.
> - [ ] Mock-Up oluştur.

**Comment by bibuggy** [comment]
> Mock-up nedir? Ne işe yarar? Nerelerde kullanılır?

> Tasarımın başlangıcından sonucuna kadar eşlik edecek olan modelleme sürecidir. Üzerinde çalışacağımız projenin wireframeini oluşturmak için kullanılır.

> Peki Wireframe nedir?

> Wireframe bir yazılım projesinin çalışmayan taslak halidir.

> Kısaca bir web sitesinin masaüstü veya herhangi bir sitede nasıl görüneceğini gösteren şablonlara mock-up adı verilmektedir.

**Comment by bibuggy** [comment]
> Projenin mock-up'ına <a href="https://moqups.com/meryem.saka@bil.omu.edu.tr/nSeXnkKW" title="MOCK-UP">buradan</a> ulaşabilirsiniz.

**Comment by bibuggy** [comment]
## Bu iş kaydını anlatıldığı şekilde düzenle.

**Comment by merbussa** [comment]
Mock-up nedir? Ne işe yarar? Nerelerde kullanılır?

Tasarımın başlangıcından sonucuna kadar eşlik edecek olan modelleme sürecidir. Üzerinde çalışacağımız projenin wireframeini oluşturmak için kullanılır.

Peki Wireframe nedir?

Wireframe bir yazılım projesinin çalışmayan taslak halidir.

Kısaca bir web sitesinin masaüstü veya herhangi bir sitede nasıl görüneceğini gösteren şablonlara mock-up adı verilmektedir.

**Comment by merbussa** [comment]
Mock-up tasarımı tamamlandı. Projenin mock-up'ına <a href="https://moqups.com/meryem.saka@bil.omu.edu.tr/nSeXnkKW" title="MOCK-UP">buradan</a> ulaşabilirsiniz.

**Comment by mrym-bsr** [comment]
# İş kaydı istenilen şekilde düzenlendi.
